version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-cli-buster # Use PHP version that matches your project requirements
    working_directory:  ~/backend
    steps:
      # Checkout the project code
      - checkout
      - run:
         name: Check Directory Contents
         command: ls -la 
      # Install dependencies with Composer
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install

      # Validate composer.json and composer.lock
      - run:
          name: Validate composer.json and composer.lock
          command: composer validate --strict

      # Run PHPUnit tests
      - run:
          name: Run PHPUnit Tests
          command: |
            if [ -f vendor/bin/phpunit ]; then
              vendor/bin/phpunit
            else
              echo "PHPUnit not found, please check if it is installed."
            fi

      # Store test results for PHPUnit
      - store_test_results:
          path: tests/_output

      # Store artifacts (e.g., code coverage reports)
      - store_artifacts:
          path: tests/_output

workflows:
  version: 2
  build:
    jobs:
      - build
