version: 2.1

orbs:
  php: circleci/php@1.1.0

jobs:
  test-php:
    docker:
      - image: cimg/php:8.2.7
    steps:
      - checkout

      # Install Composer
      - php/install-composer:
          install-version: 1.10.16

      # Install Dependencies
      - run:
          name: Install Dependencies
          command: |
            cd backend
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install

     

      # Set Permissions for PHPUnit
      - run:
          name: Set permissions for PHPUnit
          command: |
             cd backend
             chmod +x ./vendor/bin/phpunit

      # Run PHPUnit with Code Coverage
      - run:
          name: Run PHPUnit Tests with Code Coverage
          command: |
            cd backend
            ./vendor/bin/phpunit --coverage-clover=coverage.xml

      # Store test results
      - store_test_results:
          path: backend/coverage.xml

      # Store artifacts
      - store_artifacts:
          path: backend/coverage.xml
          destination: test-results

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-php
