version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-cli-buster # Use the desired PHP version, e.g., PHP 8.0
    steps:
      - checkout

      # Install dependencies using Composer
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install
      
      # Run tests (if applicable)
      - run:
          name: Run Tests
          command: vendor/bin/phpunit

      # Build the project (adjust according to your project structure)
      - run:
          name: Build Project
          command: |
            php build.php  # Replace this with your specific build command

workflows:
  version: 2
  build:
    jobs:
      - build
