version: 2.1

orbs:
  php: circleci/php@1.1.0

jobs:
  test-php:
    docker:
      - image: cimg/php:8.2.7
    steps:
      - checkout

      - php/install-composer:
          install-version: 1.10.16  # Ensure correct usage of key-value format

      - run:
          name: Install Dependencies
          command: |
            cd backend
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install

      - run:
          name: Install Xdebug for Code Coverage
          command: |
            sudo apt-get install -y php-xdebug
            php -m | grep xdebug  # Verify Xdebug installation

      - run:
          name: Set permissions for PHPUnit
          command: |
             cd backend
             chmod +x ./vendor/bin/phpunit

      - run:
          name: Run PHPUnit Tests with Code Coverage
          command: |
            cd backend
            ./vendor/bin/phpunit --coverage-text

      - store_test_results:
          path: test-results.xml

      - store_artifacts:
          path: test-results.xml
          destination: test-results

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-php
