version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-cli-buster
    steps:
      - checkout

      # Check if composer.json exists, and install dependencies only if present
      - run:
          name: Check for composer.json and Install Dependencies
          command: |
            if [ -f composer.json ]; then
              curl -sS https://getcomposer.org/installer | php
              php composer.phar install
            else
              echo "No composer.json found, skipping dependency installation"
            fi
      
      # Run tests if composer.json and PHPUnit are present
      - run:
          name: Run Tests
          command: |
            if [ -f composer.json ] && [ -f vendor/bin/phpunit ]; then
              vendor/bin/phpunit
            else
              echo "No PHPUnit or composer.json found, skipping tests"
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
