name: PHP Composer

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install dependencies
      working-directory: backend
      run: composer install --prefer-dist --no-progress
    - name: Generate key
      # working-directory: backend
      run: php artisan key:generate
      
    - name: Execute tests (Unit and Feature test) via PHPUnit
      working-directory: backend
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Create coverage artifact
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: backend/coverage.xml
